# Generated by Django 3.2.4 on 2021-08-05 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200, null=True)),
                ('contact_name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.PositiveIntegerField(null=True)),
                ('company_registration_number', models.CharField(max_length=200, null=True)),
                ('vat_no', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('bank_account_number', models.PositiveIntegerField(null=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('bank_branch', models.CharField(max_length=50, null=True)),
                ('nic_number', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
